apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec:
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      name: pod-web-server
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
      - name: my-container-nginx
        image: tomcat
      nodeName: minikube-m02

  selector:
    matchLabels:
      apps: my-app

