apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 8
  selector:
    matchLabels:
      env: production
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.20.3
